### ISSUE TITLE
[tutorial] Wording awkward in Quickstart regarding placement in "layout/step-1"

### ISSUE THREAD

**Issue by lenards** [lore/lore#174]
_This is feedback that could be ignore if desired._

For Lore Quickstart, the placement instruction at this juncture have a continuity quirk. The instructions say: 

> Now add the following scripts at the bottom of the <body> tag, immediately above the bundle.js script.

source: http://www.lorejs.org/quickstart/layout/step-1/

But there isn't a _"bundle.js"_ yet in `index.html`. 

There _is_ an HTML comment that mentions the script tags for the `/bundle.{vendor,main}.{:hash}.js`. So that might be what is meant for _anchoring_ the action. 

Any confusion that could occur is most likely eliminated thanks clarifications in "Code Changes" section.

**Comment by lenards** [comment]
I'm almost willing to "self-close" this. Sorry ... it's the former teacher in me that decided to write it up. All the other aspects so far as done with such care and clarity, I just thought I'd mention it.

**Comment by jchansen** [comment]
@lenards glad you did! It's a good callout. I'll leave this open and fix that soon to replace the text with something like:

> Now add the following scripts to the bottom of the `<body>` tag.

**Comment by lenards** [comment]
That works!

**Comment by jchansen** [comment]
Closing as this has been fixed in the new website by making the suggested change.
